image: Visual Studio 2022

# Adds "+build.XXX" to MinVer's build metadata
environment:
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%

# AppVeyor's displayed version, will get updated by MSBuild target
version: '{build}'

before_build:
- choco install dotnet-sdk --version 8.0.100-rc2235022 --pre
- dotnet restore

build_script:
- dotnet pack --no-restore --configuration Release -p:ContinuousIntegrationBuild=true

test_script:
- dotnet test --no-build --configuration Release -p:CollectCoverage=true

after_test:
- choco install codecov
- pwsh: codecov --file @(ls artifacts/coverage/*.opencover.xml)

artifacts:
- path: artifacts/package/**/*.nupkg
